admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
fos_user_security:
    resource: "@UserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@UserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    


fos_user_register:
    resource: "@UserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    

    
fos_user_resetting:
    resource: "@UserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@UserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
AbdouUserBundle:
    resource: "@UserBundle/Resources/config/routing/routing.yml"
    prefix:   /
    
fos_user_Pres:
    resource: "@UserBundle/Resources/config/routing/registrationPres.xml"
    prefix: /registerPres